@baseUrl = http://localhost:8000/api

GET {{baseUrl}}/subscriptions

###

POST {{baseUrl}}/subscriptions
Content-Type: application/json

{
    "name": "Youtube Premium",
    "category": "entertainment",
    "price": 13.99,
    "icon": "https://www.freepnglogos.com/uploads/youtube-icon-png-12.png"
}

###
GET {{baseUrl}}/subscriptions/1